// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfqUpuKul9doxiFToXr_w5u4j2Eru3uzw',
    appId: '1:980764920917:web:e15c0e5abca9060e2318dc',
    messagingSenderId: '980764920917',
    projectId: 'arcygnus-assets',
    authDomain: 'arcygnus-assets.firebaseapp.com',
    databaseURL: 'https://arcygnus-assets.firebaseio.com',
    storageBucket: 'arcygnus-assets.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaGRKU4aAN6JZbPBGURByCL_9xHO3echM',
    appId: '1:980764920917:android:5b6ed5bc7e3e5c8e2318dc',
    messagingSenderId: '980764920917',
    projectId: 'arcygnus-assets',
    databaseURL: 'https://arcygnus-assets.firebaseio.com',
    storageBucket: 'arcygnus-assets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiZ6V552wj7_qX1m07Na4qONFaYr4ZC00',
    appId: '1:980764920917:ios:e4c9f03092b939852318dc',
    messagingSenderId: '980764920917',
    projectId: 'arcygnus-assets',
    databaseURL: 'https://arcygnus-assets.firebaseio.com',
    storageBucket: 'arcygnus-assets.appspot.com',
    iosClientId: '980764920917-08qdrhjipakfo28ua1p26bmdas0ankrc.apps.googleusercontent.com',
    iosBundleId: 'com.aneesh.dynamicCachedFontsExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiZ6V552wj7_qX1m07Na4qONFaYr4ZC00',
    appId: '1:980764920917:ios:e4c9f03092b939852318dc',
    messagingSenderId: '980764920917',
    projectId: 'arcygnus-assets',
    databaseURL: 'https://arcygnus-assets.firebaseio.com',
    storageBucket: 'arcygnus-assets.appspot.com',
    iosClientId: '980764920917-08qdrhjipakfo28ua1p26bmdas0ankrc.apps.googleusercontent.com',
    iosBundleId: 'com.aneesh.dynamicCachedFontsExample',
  );
}
